apiVersion: v2
name: postgres-operator
description: 'PGO: The Postgres Operator from RadonDB Helm Chart for Kubernetes'
type: application
version: 0.2.1
appVersion: 4.7.1
home: https://github.com/radondb/radondb-postgresql-operator
icon: https://github.com/radondb/radondb-postgresql-operator/raw/master/docs/static/logos/pgo.svg
keywords:
    - PostgreSQL
    - Operator
    - Database
    - Postgres
    - SQL
    - NoSQL
    - RDBMS
