apiVersion: v1
name: nodeagent
version: 1.4.8
appVersion: 1.4.8
tillerVersion: ">=2.7.2"
description: Helm chart for nodeagent deployment
keywords:
  - istio
  - nodeagent
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
