apiVersion: v1
kind: Service
metadata:
  name: ks-devops
  annotations:
    desc: ''
  namespace: kubesphere-devops-system
  labels:
    app: ks-devops
    tier: backend
    version: advanced-1.0.0
spec:
  selector:
    app: ks-devops
    tier: backend
    version: advanced-1.0.0
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  sessionAffinity: None