apiVersion: application.kubesphere.io/v1alpha1
kind: OperatorApplication
metadata:
  name: postgresql
  labels:
    category_id: radondb
spec:
  # Add fields here
  name: "RadonDB PostgreSQL"
  description_zh: "一款基于 PostgreSQL 的容器化、开源关系型数据库。"
  description: "A cloud-native, powerful, open source object-relational database system based on PostgreSQL."
  abstraction_zh: |
    - 被广泛应用于地理空间和移动领域
    - 具备高可用、稳定性、数据完整性等性能
    - 支持在线水平扩展
    - 支持故障自动转移 ，提供 HA 功能
    - 提供 PostgreSQL 常用参数接口，方便调整参数
    - 提供 PostGIS 插件，具备存储、查询和修改空间关系的能力
    - 提供实时监控、健康检查、日志自动清理等功能
  abstraction: |
    - It is  widely used in geospatial and mobile fileds.
    - Provide  features such as high availability, data stability and integrity .
    - Support online horizontal scaling.
    - Support auto-failover and HA.
    - Provide PostgreSQL common APIs to facilitate parameter adjustment.
    - Provide PostGIS plug-in to store, query and modify spatial relationships.
    - Provide functions such as real-time monitoring, health check and automatic log clearing.
  screenshots: |
    /assets/screenshots/radondb_list.jpg,/assets/screenshots/pg_create.jpg,/assets/screenshots/pg_detail.jpg,/assets/screenshots/pg_monitor.jpg
  screenshots_zh: |
    /assets/screenshots/radondb_list_zh.jpg,/assets/screenshots/pg_create_zh.jpg,/assets/screenshots/pg_detail_zh.jpg,/assets/screenshots/pg_monitor_zh.jpg
  icon: "/assets/radondb_logo.svg"
  owner: "RadonDB"
status:
  latestVersion: "2.0"
  state: active
