{{- if .Values.exporter.enabled }}
apiVersion: events.kubesphere.io/v1alpha1
kind: Exporter
metadata:
  name: {{ template "kube-events.exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kube-events.labels" . | indent 4 }}
spec:
  {{- if .Values.exporter.image }}
  image: {{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag | default (print "v" .Chart.AppVersion) }}
  imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
  {{- end }}
  {{- if .Values.exporter.affinity }}
  affinity:
{{ toYaml .Values.exporter.affinity | indent 4 }}
  {{- end }}
  {{- if .Values.exporter.nodeSelector }}
  nodeSelector:
{{ toYaml .Values.exporter.nodeSelector | indent 4 }}
  {{- end }}
  {{- if .Values.exporter.tolerations }}
  tolerations:
{{ toYaml .Values.exporter.tolerations | indent 4 }}
  {{- end }}
  {{- if .Values.exporter.resources }}
  resources:
{{ toYaml .Values.exporter.resources | indent 4 }}
  {{- end }}
{{- if .Values.exporter.volumes }}
  volumes:
{{ toYaml .Values.exporter.volumes | indent 2 }}
{{- end }}
{{- if .Values.exporter.volumeMounts }}
  volumeMounts:
{{ toYaml .Values.exporter.volumeMounts | indent 2 }}
{{- end }}
{{- if .Values.timezone }}
  env:
  - name: TZ
    value: {{ .Values.timezone }}
{{- end }}
  sinks:
    {{- if .Values.exporter.sinks.stdout.enabled }}
    stdout: {}
    {{- end }}
    {{- if or .Values.ruler.enabled (not (empty .Values.exporter.sinks.additionalWebhooks)) }}
    webhooks:
    {{- if .Values.ruler.enabled }}
    - service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "kube-events.ruler.fullname" . }}
        port: 8443
        path: /events
    {{- end }}
    {{- with .Values.exporter.sinks.additionalWebhooks }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- end }}
{{- end }}