{{- if .Values.ruler.enabled }}
apiVersion: events.kubesphere.io/v1alpha1
kind: Ruler
metadata:
  name: {{ template "kube-events.ruler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kube-events.labels" . | indent 4 }}
spec:
{{- if .Values.ruler.image }}
  image: {{ .Values.ruler.image.repository }}:{{ .Values.ruler.image.tag | default (print "v" .Chart.AppVersion) }}
  imagePullPolicy: {{ .Values.ruler.image.pullPolicy }}
{{- end }}
  replicas: {{ .Values.ruler.replicas }}
  {{- if .Values.ruler.affinity }}
  affinity:
{{ toYaml .Values.ruler.affinity | indent 4 }}
  {{- end }}
  {{- if .Values.ruler.nodeSelector }}
  nodeSelector:
{{ toYaml .Values.ruler.nodeSelector | indent 4 }}
  {{- end }}
  {{- if .Values.ruler.tolerations }}
  tolerations:
{{ toYaml .Values.ruler.tolerations | indent 4 }}
  {{- end }}
  {{- if .Values.ruler.resources }}
  resources:
{{ toYaml .Values.ruler.resources | indent 4 }}
  {{- end }}
{{- if .Values.ruler.volumes }}
  volumes:
{{ toYaml .Values.ruler.volumes | indent 2 }}
{{- end }}
{{- if .Values.ruler.volumeMounts }}
  volumeMounts:
{{ toYaml .Values.ruler.volumeMounts | indent 2 }}
{{- end }}
{{- if .Values.timezone }}
  env:
  - name: TZ
    value: {{ .Values.timezone }}
{{- end }}
  ruleNamespaceSelector:
{{ toYaml .Values.ruler.ruleNamespaceSelector | indent 4 }}
  ruleSelector:
{{ toYaml .Values.ruler.ruleSelector | indent 4 }}
  sinks:
    {{- with .Values.ruler.sinks.alertmanager }}
    alertmanager:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- if not (empty .Values.ruler.sinks.alertmanagers) }}
    alertmanagers:
{{ toYaml .Values.ruler.sinks.alertmanagers | indent 4 }}
    {{- end }}
    {{- if not (empty .Values.ruler.sinks.webhooks) }}
    {{- with .Values.ruler.sinks.webhooks }}
    webhooks:
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- end }}
    {{- with .Values.ruler.sinks.stdout }}
    stdout:
{{ toYaml . | indent 6 }}
    {{- end }}
{{- end }}
