apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: edge-watcher-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /edge-watcher
        image: {{ .Values.edgeWatcher.controllerManager.repository }}:{{ .Values.edgeWatcher.controllerManager.tag }}
        imagePullPolicy: {{ .Values.edgeWatcher.controllerManager.pullPolicy }}
        name: edge-watcher
        env:
        - name: VERSION
          value: {{ .Values.cloudCore.tag }}
        - name: REGION
          value: zh
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: host-time
        - name: config
          mountPath: /etc/edgewatcher/config
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: {{ .Values.edgeWatcher.kubeRBACProxy.repository }}:{{ .Values.edgeWatcher.kubeRBACProxy.tag }}
        imagePullPolicy: {{ .Values.edgeWatcher.kubeRBACProxy.pullPolicy }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        volumeMounts:
        - mountPath: /etc/localtime
          name: host-time
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      {{- with .Values.edgeWatcher.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.edgeWatcher.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time
      - name: config
        configMap:
          name: edge-watcher