apiVersion: application.kubesphere.io/v1alpha1
kind: OperatorApplication
metadata:
  name: mysql
spec:
  # app name
  name: "MySQL"
  # app description
  description: "一款基于 MySQL 提供的企业级数据库。"
  description_en: "A cloud-native, enterprise-class database system based on MySQL."
  # app description
  abstraction: |
    - 提供一主多从高可用架构
    - 金融级 MySQL 集群
    - 提供 Semi-Sync 插件，确保节点间的数据一致性
    - 提供一主多从架构，基于 Raft 协议管理集群节点，具备主从秒级切换性能，保障业务连续性
    - 提供自动备份、监控告警等功能
  abstraction_en: |
    - Provide a high availability architecture with one master and multiple slave nodes.
    - Provide financial high reliable MySQL cluster.
    - Provide Semi-Sync plug-in to ensure data consistency between nodes.
    - Support master/slave switchover in seconds to ensure service continuity that based on Raft protocol.
    - Provide functions such as automatic backup and alarm monitoring.
  operator: "admin"
  icon: "https://raw.githubusercontent.com/radondb/radondb-mysql-kubernetes/main/docs/images/logo_radondb-mysql.png"
  owner: "RadonDB"
status:
  state: active
