apiVersion: application.kubesphere.io/v1alpha1
kind: OperatorApplicationVersion
metadata:
  name: mysql
  labels:
    category_id: radondb
spec:
  name: "MySQL"
  screenshots: |
    - https://github.com/radondb/radondb-clickhouse-kubernetes/raw/main/document/_images/logo_radondb.svg
    - https://github.com/radondb/radondb-clickhouse-kubernetes/raw/main/document/_images/logo_radondb.svg
    - https://github.com/radondb/radondb-clickhouse-kubernetes/raw/main/document/_images/logo_radondb.svg
  screenshots_zh: |
    - https://github.com/radondb/radondb-clickhouse-kubernetes/raw/main/document/_images/logo_radondb.svg
  changeLog: |
    - Add serviceMonitor for operator #169 #174
    - Backup to S3 and restore from S3 #116 #144 #197
    - Add ci for images management and greeting. #207
    - Support user management through crd. #175 #198 #228
    - Support extranet access service. #251 #252
    - Make the cluster state cover more scenarios. #253 #264
  changeLog_zh: |
    - Add serviceMonitor for operator #169 #174
    - Backup to S3 and restore from S3 #116 #144 #197
    - Add ci for images management and greeting. #207
    - Support user management through crd. #175 #198 #228
    - Support extranet access service. #251 #252
    - Make the cluster state cover more scenarios. #253 #264
  operatorVersion: "2.1.0"
  appVersion: "5.7.34"
  owner: "RadonDB"
status:
  state: active
