---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: postgresqlclusters.pgcluster.kubesphere.io
spec:
  group: pgcluster.kubesphere.io
  names:
    kind: PostgreSQLCluster
    listKind: PostgreSQLClusterList
    plural: postgresqlclusters
    singular: postgresqlcluster
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: PostgreSQLCluster is the Schema for the postgresqlclusters API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: PostgreSQLClusterSpec defines the desired state of PostgreSQLCluster
              properties:
                action:
                  type: string
                allFlag:
                  type: boolean
                autofail:
                  type: integer
                ccpImage:
                  type: string
                ccpImageTag:
                  type: string
                clusterName:
                  description: '******** update cluster'
                  items:
                    type: string
                  type: array
                cpuLimit:
                  type: string
                cpuRequest:
                  type: string
                database:
                  type: string
                delete-data:
                  type: string
                deleteBackups:
                  type: boolean
                deleteData:
                  type: boolean
                managedUser:
                  type: boolean
                memoryLimit:
                  type: string
                memoryRequest:
                  type: string
                name:
                  description: '******** create cluster params ******** ClientVersion
                  string `json:"clientVersion,omitempty"` cluster name'
                  type: string
                namespace:
                  type: string
                nodeLabel:
                  description: '******** scale cluster'
                  type: string
                password:
                  type: string
                passwordAgeDays:
                  type: integer
                passwordLength:
                  type: integer
                passwordType:
                  type: string
                pgVersion:
                  type: string
                podAnnotation:
                  items:
                    additionalProperties:
                      type: string
                    type: object
                  type: array
                postgresqlParams:
                  type: string
                pvcSize:
                  type: string
                replicaCount:
                  type: integer
                replicaName:
                  description: '******** scale down'
                  type: string
                restart:
                  description: '******** restart cluster'
                  type: boolean
                rollingUpdate:
                  type: boolean
                selector:
                  description: '******** delete cluster ClusterName   string `json:"clusterName"`'
                  type: string
                serviceType:
                  type: string
                setSystemAccountPassword:
                  description: '******** update user'
                  type: boolean
                showSystemAccounts:
                  description: '******** show user'
                  type: boolean
                shutdown:
                  type: boolean
                startup:
                  type: boolean
                storageConfig:
                  type: string
                syncReplication:
                  type: boolean
                targets:
                  items:
                    type: string
                  type: array
                tolerations:
                  items:
                    description: The pod this Toleration is attached to tolerates any
                      taint that matches the triple <key,value,effect> using the matching
                      operator <operator>.
                    properties:
                      effect:
                        description: Effect indicates the taint effect to match. Empty
                          means match all taint effects. When specified, allowed values
                          are NoSchedule, PreferNoSchedule and NoExecute.
                        type: string
                      key:
                        description: Key is the taint key that the toleration applies
                          to. Empty means match all taint keys. If the key is empty,
                          operator must be Exists; this combination means to match all
                          values and all keys.
                        type: string
                      operator:
                        description: Operator represents a key's relationship to the
                          value. Valid operators are Exists and Equal. Defaults to Equal.
                          Exists is equivalent to wildcard for value, so that a pod
                          can tolerate all taints of a particular category.
                        type: string
                      tolerationSeconds:
                        description: TolerationSeconds represents the period of time
                          the toleration (which must be of effect NoExecute, otherwise
                          this field is ignored) tolerates the taint. By default, it
                          is not set, which means tolerate the taint forever (do not
                          evict). Zero and negative values will be treated as 0 (evict
                          immediately) by the system.
                        format: int64
                        type: integer
                      value:
                        description: Value is the taint value the toleration matches
                          to. If the operator is Exists, the value should be empty,
                          otherwise just a regular string.
                        type: string
                    type: object
                  type: array
                username:
                  type: string
                users:
                  description: '******** create user'
                  items:
                    properties:
                      password:
                        type: string
                      username:
                        type: string
                    required:
                      - password
                      - username
                    type: object
                  type: array
              required:
                - name
                - namespace
              type: object
            status:
              description: PostgreSQLClusterStatus defines the observed state of PostgreSQLCluster
              properties:
                condition:
                  items:
                    description: ApiResult defines the result of pg operator ApiServer
                    properties:
                      api:
                        type: string
                      code:
                        type: string
                      data:
                        type: string
                      msg:
                        type: string
                    type: object
                  type: array
                state:
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
