appVersion: 1.7.5
description: An open source trusted cloud native registry that stores, signs, and
  scans content
engine: gotpl
home: https://goharbor.io
icon: https://raw.githubusercontent.com/goharbor/harbor/master/docs/img/harbor_logo.png
keywords:
  - docker
  - registry
  - harbor
maintainers:
  - email: huh@vmware.com
    name: Jesse Hu
  - email: username.taken@gmail.com
    name: paulczar
name: harbor
sources:
  - https://github.com/goharbor/harbor
  - https://github.com/goharbor/harbor-helm
version: 1.0.1
