{{- $cn := printf "%s.%s.svc" ( include "logsidecar-injector.admission.fullname" . ) .Release.Namespace }}
{{- $ca := genCA "logsidecar-injector-admission-ca" 3650 -}}
{{- $cert := genSignedCert $cn nil nil 3650 $ca -}}
apiVersion: v1
data:
  server.crt: {{ b64enc $cert.Cert }}
  server.key: {{ b64enc $cert.Key }}
kind: Secret
metadata:
  name: {{ template "logsidecar-injector.admission.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logsidecar-injector.labels" . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "logsidecar-injector.admission.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logsidecar-injector.labels" . | indent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    logging.kubesphere.io/logsidecar-injector: {{ template "logsidecar-injector.deploy.fullname" . }}
{{ include "logsidecar-injector.labels" . | indent 4 }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "logsidecar-injector.admission.fullname" . }}-mutate
  labels:
{{ include "logsidecar-injector.labels" . | indent 4 }}
webhooks:
  - name: logsidecar-injector.logging.kubesphere.io
    failurePolicy: Fail
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "logsidecar-injector.admission.fullname" . }}
      caBundle: {{ b64enc $ca.Cert }}
    namespaceSelector:
      matchExpressions:
      - key: logging.kubesphere.io/logsidecar-injection
        operator: In
        values:
        - enabled
    objectSelector:
      matchExpressions:
      - key: logging.kubesphere.io/logsidecar-injector
        operator: DoesNotExist
