- name: ks-upgrade | disable ks-apiserver
  shell: "{{ bin_dir }}/kubectl -n kubesphere-system scale deployment ks-apiserver --replicas=0"
  failed_when: false


- name: ks-upgrade | disable ks-console
  shell: "{{ bin_dir }}/kubectl -n kubesphere-system scale deployment ks-console --replicas=0"
  failed_when: false


- name: ks-upgrade | disable ks-controller-manager
  shell: "{{ bin_dir }}/kubectl -n kubesphere-system scale deployment ks-controller-manager --replicas=0"
  failed_when: false
