---

monitoring:
  prometheusReplica: 2
  prometheusMemoryRequest: 400Mi
  prometheusVolumeSize: 20Gi
  prometheus:
    limits:
      cpu: 8
      memory: 32Gi
    requests:
      cpu: 80m
      memory: 400Mi
  node_exporter:
    limits:
      cpu: 600m
      memory: 500Mi
    requests:
      cpu: 51m
      memory: 180Mi
  kube_rbac_proxy:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 20Mi 
  kube_state_metrics:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 50m
      memory: 150Mi 
  prometheus_adapter:
    limits:
      cpu: 600m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 250Mi 
  alertmanager:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 30Mi 
  grafana:
    enable: false

etcd.endpointIps: |-
  {% for item in groups['etcd'] -%}
    {{ hostvars[item]['access_ip'] | default(hostvars[item]['ip'] | default(hostvars[item]['ansible_default_ipv4']['address'])) }}{% if not loop.last %},{% endif %}
  {%- endfor %}

etcd.port: 2379
etcd.tlsEnable: true

#etcd_config_dir: /etc/ssl/etcd
#etcd_cert_dir: "{{ etcd_config_dir }}/ssl"
#etcd_client_ca_crt: "{{ etcd_cert_dir }}/ca.pem"
#etcd_client_crt: "{{ etcd_cert_dir }}/node-{{ inventory_hostname }}.pem"
#etcd_client_key: "{{ etcd_cert_dir }}/node-{{ inventory_hostname }}-key.pem"

