apiVersion: v1
kind: Service
metadata:
  annotations:
    creator: admin
    desc: ""
  labels:
    app: kubesphere
    component: ks-docs
  name: ks-docs
  namespace: kubesphere-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: kubesphere
    component: ks-docs
    tier: backend
  sessionAffinity: None
  type: ClusterIP
