---

- name: ks-notification | Getting ks-notification installation files
  copy:
    src: "{{ item }}"
    dest: "{{ kubesphere_dir }}/"
  loop:
    - notification
  tags:
    - upgrade

- name: ks-notification | Checking notification-svc
  shell: >
    {{ bin_dir }}/kubectl get svc -n kubesphere-alerting-system
  register: notification_svc
  failed_when: false

- name: ks-notification | Checking notification image version
  shell: >
    {{ bin_dir }}/kubectl get deploy -n kubesphere-alerting-system notification-deployment 
    -o=jsonpath='{.spec.template.spec.containers[0].image}'
  register: notification_image
  failed_when: false

- import_tasks: save-config.yaml
  when:
    - notification_svc.stdout.find("notification") != -1
    - notification_image.stdout.find("notification:advanced-2.0.0") != -1

- name: ks-notification | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/notification/{{ item.file }}"
  with_items:
    - { type: apiserver, file: notification.yaml }
    - { type: ctrl, file: notification-db-ctrl-job.yaml }
    - { type: init, file: notification-db-init-job.yaml }
  tags:
    - upgrade

- name: ks-notification | Checking db-ctrl-job
  shell: "{{ bin_dir }}/kubectl get job -n kubesphere-alerting-system"
  register: result
  tags:
    - upgrade

- name: ks-notification | Delete db-ctrl-job
  shell: "{{ bin_dir }}/kubectl -n kubesphere-alerting-system delete jobs.batch notification-db-ctrl-job"
  when: result.stdout.find("notification-db-ctrl-job") != -1
  tags:
    - upgrade

- name: ks-notification | Delete db-init-job
  shell: "{{ bin_dir }}/kubectl -n kubesphere-alerting-system delete jobs.batch notification-db-init-job"
  when: result.stdout.find("notification-db-init-job") != -1
  tags:
    - upgrade

- name: ks-notification | Init ks-notification
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/notification/notification-db-init-job.yaml"

- name: ks-notification | Ctrl ks-notification
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/notification/notification-db-ctrl-job.yaml"
  tags:
    - upgrade

- name: ks-notification | Deploy ks-notification
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/notification/notification.yaml"
  tags:
    - upgrade


- name: ks-notification | Import ks-notification status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"notification": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kubesphere-system
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3