apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-operator.fullname" . }}
  labels:
    {{- include "mongodb-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "mongodb-operator.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.operator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mongodb-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.registry }}
      imagePullSecrets:
        - name: {{ .Values.registry.secretName }}
      {{- end }}
      serviceAccountName: {{ include "mongodb-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          command:
            - /usr/local/bin/entrypoint
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          image: "{{ if .Values.registry }}{{ .Values.registry.prefix}}{{"/"}}{{ else if .Values.image.prefix}}{{ .Values.image.prefix}}{{"/"}}{{ end }}{{ .Values.image.operator.name}}:{{ .Values.image.operator.version}}"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          env:
          {{- if .Values.operator.extraEnvs }}
            {{- toYaml .Values.operator.extraEnvs | nindent 12}}
          {{- end }}
          {{- if .Values.operator.watchNamespace }}
            - name: WATCH_NAMESPACE
              value: "{{.Values.operator.watchNamespace }}"
          {{- else }}
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_IMAGE
              value: "{{ if .Values.registry }}{{ .Values.registry.prefix}}{{"/"}}{{ else if .Values.image.prefix }}{{ .Values.image.prefix}}{{"/"}}{{ end }}{{ .Values.image.agent.name }}:{{ .Values.image.agent.version }}"
            - name: VERSION_UPGRADE_HOOK_IMAGE
              value: "{{ if .Values.registry }}{{ .Values.registry.prefix}}{{"/"}}{{ else if .Values.image.prefix}}{{ .Values.image.prefix}}{{"/"}}{{ end }}{{ .Values.image.versionUpgradeHook.name }}:{{ .Values.image.versionUpgradeHook.version }}"
            - name: READINESS_PROBE_IMAGE
              value: "{{ if .Values.registry }}{{ .Values.registry.prefix}}{{"/"}}{{ else if .Values.image.prefix}}{{ .Values.image.prefix}}{{"/"}}{{ end }}{{ .Values.image.readinessProbe.name }}:{{ .Values.image.readinessProbe.version }}"
            - name: MONGODB_IMAGE
              value: "{{ .Values.image.mongodb.name}}"
            - name: MONGODB_REPO_URL
              value: "{{ if .Values.registry }}{{ .Values.registry.prefix}}{{ else if .Values.image.prefix}}{{ .Values.image.prefix}}{{ end }}"
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}