---
apiVersion: v1
data:
  ks-config.yaml: |
    kube_apiserver_host: 192.168.0.2:6443
    etcd_tls_enable: True
    etcd_endpoint_ips: 192.168.0.2
    disableMultiLogin: True
    elk_prefix: logstash
    persistence:
      enable: false
      storageClass: ""
kind: ConfigMap
metadata:
  name: kubesphere-config
  namespace: kubesphere-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ks-installer
  namespace: kubesphere-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ks-installer
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tenant.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - devops.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - logging.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - jaegertracing.io
  resources:
  - '*'
  verbs:
  - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ks-installer
subjects:
- kind: ServiceAccount
  name: ks-installer
  namespace: kubesphere-system
roleRef:
  kind: ClusterRole
  name: ks-installer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: kubesphere-installer
  namespace: kubesphere-system
spec:
  template:
    spec:
      serviceAccountName: ks-installer
      containers:
      - name: ansible
        command: ["ansible-playbook", "/usr/src/kubesphere/kubesphere.yaml", "-b", "-e", "@/usr/src/kubesphere/conf/ks-config.yaml"]
        image: "kubespheredev/ks-installer:advanced-2.0.2"
        imagePullPolicy: "Always"
        volumeMounts:
          - name: kubesphere-config
            mountPath: /usr/src/kubesphere/conf
      restartPolicy: OnFailure
      volumes:
        - name: kubesphere-config
          configMap:
            name: kubesphere-config



