---
- name: notification-history | Creates directory
  file:
    path: "{{ kubesphere_dir }}/notification-history"
    state: directory

- name: notification-history | Getting notification-history installation files
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.path }}/{{ item.file }}"
  with_items:
    - { path: notification-history, file: custom-input-notification-history.yaml }
    - { path: notification-history, file: custom-filter-notification-history.yaml }
    - { path: notification-history, file: custom-output-notification-history.yaml }
    - { path: notification-history, file: adapter.yaml }

- name: notification-history | Install notification-history
  shell: >
     {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/notification-history/
  register: install
  failed_when: install is not succeeded

- name: notification-history | Importing notification-history status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"notification": {"history": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}, "status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kubesphere-system
  register: cc_result
  when:
    - install is succeeded
  failed_when: "cc_result.stderr and 'Warning' not in cc_result.stderr"
  until: cc_result is succeeded
  retries: 5
  delay: 3
