apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-controller-manager
    app.kubernetes.io/vendor: kubesphere
  name: kube-controller-manager
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
  - interval: 1m
    metricRelabelings:
    - action: keep
      regex: up
      sourceLabels:
      - __name__
    port: http-metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kube-controller-manager
