---
- name: Monitoring | Installing devops monitoring
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/prometheus/{{ item }}"
  loop:
    - "devops"
  register: devops_result
  failed_when: "devops_result.stderr and 'Warning' not in devops_result.stderr and 'spec.clusterIP' not in devops_result.stderr"
  until: devops_result is succeeded
  retries: 5
  delay: 3
  when:
    - devops.enabled is defined
    - devops.enabled == true