---
- name: ks-monitor | Getting monitor installation files
  copy:
    src: "{{ item }}"
    dest: "{{ kubesphere_dir }}/"
  loop:
    - "prometheus"

- import_tasks: get_old_config.yaml

- name: ks-monitor | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.path }}/{{ item.file }}"
  with_items:
    - { path: prometheus/init, file: prometheus-operator-deployment.yaml }
    - { path: prometheus/prometheus, file: prometheus-prometheus.yaml }
    - { path: prometheus/kube-state-metrics, file: kube-state-metrics-deployment.yaml }
    - { path: prometheus/node-exporter, file: node-exporter-daemonset.yaml }
    - { path: prometheus/alertmanager, file: alertmanager-alertmanager.yaml }
    - { path: prometheus/prometheus-adapter, file: prometheus-adapter-deployment.yaml }
    - { path: prometheus/grafana, file: grafana-deployment.yaml }
    - { path: prometheus/etcd, file: prometheus-serviceMonitorEtcd.yaml }
    - { path: prometheus/etcd, file: prometheus-endpointsEtcd.yaml }