---

- name: notification-manager | Getting notification-manager installation files
  copy:
    src: "notification-manager"
    dest: "{{ kubesphere_dir }}/"

- name: notification-manager | Getting federated files
  copy:
    src: "federated"
    dest: "{{ kubesphere_dir }}/"

- name: notification-manager | Getting notification-manager installation files
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.path }}/{{ item.file }}"
  with_items:
    - { path: notification-manager, file: custom-values-notification.yaml }


- name: notification-manager | Checking notification-manager
  shell: >
    {{ bin_dir }}/helm list -f notification-manager -n kubesphere-monitoring-system
  register: notification_check
  failed_when: notification_check.rc != 0

- name: notification-manager | Update notification-manager crds
  shell: >
     {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/notification-manager/crds/
  register: update_crds
  when:
    - notification_check.rc == 0
  failed_when: update_crds is not succeeded

- name: notification-manager | Deploying notification-manager
  shell: >
    {{ bin_dir }}/helm upgrade --install notification-manager
    {{ kubesphere_dir }}/notification-manager
    -f {{ kubesphere_dir }}/notification-manager/custom-values-notification.yaml
    -n kubesphere-monitoring-system
    --force
  register: deploy_result
  until: deploy_result is succeeded
  retries: 3
  delay: 10
  when:
    - notification_check.rc == 0
    - notification_check.stdout.find("2.3.0") == -1

- name: notification-manager | Checking federatednamespace crd installed
  shell: >
    {{ bin_dir }}/kubectl get crd federatednamespaces.types.kubefed.io -o jsonpath='{.metadata.name}'
  register: crd_installed
  failed_when: false

- name: notification-manager | Deploying federatednamespace crd
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/federated/federatednamespaces.yaml"
  register: fed_result
  failed_when: "fed_result.stderr and 'Warning' not in fed_result.stderr and 'spec.clusterIP' not in fed_result.stderr"
  until: fed_result is succeeded
  retries: 5
  delay: 3
  when:
    - multicluster is defined and multicluster.clusterRole == 'host'
    - crd_installed.rc != 0 or crd_installed.stdout.find("federatednamespaces.types.kubefed.io") == -1

- name: notification-manager | Checking federated namespace deployed
  shell: >
    {{ bin_dir }}/kubectl get federatednamespaces.types.kubefed.io -n kubesphere-monitoring-federated kubesphere-monitoring-federated -o jsonpath='{.metadata.name}'
  register: namespace_deployed
  failed_when: false

- name: notification-manager | Deploying federated namespace
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/federated/kubesphere-monitoring-federated.yaml"
  register: fed_result
  failed_when: "fed_result.stderr and 'Warning' not in fed_result.stderr and 'spec.clusterIP' not in fed_result.stderr"
  until: fed_result is succeeded
  retries: 5
  delay: 3
  when:
    - multicluster is defined and multicluster.clusterRole == 'host'
    - namespace_deployed.rc != 0 or namespace_deployed.stdout.find("kubesphere-monitoring-federated") == -1

- name: notification-manager | Update federated crds
  shell: "bash {{ kubesphere_dir }}/federated/update_federated_crds.sh"
  when:
    - multicluster is defined and multicluster.clusterRole == 'host'

