---
- name: Monitoring | Installing Prometheus
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/prometheus/{{ item }}"
  loop:
    - "prometheus"
    - "prometheus"
  register: prometheus_result
  failed_when: "prometheus_result.stderr and 'Warning' not in prometheus_result.stderr and 'spec.clusterIP' not in prometheus_result.stderr"
  until: prometheus_result is succeeded
  retries: 5
  delay: 3