---

- name: ks-events | Getting ks-events installation files
  copy:
    src: "kube-events"
    dest: "{{ kubesphere_dir }}/ks-events/"

- debug:
    msg: Current Kubernetes version is {{ kubernetes_version }}


# Get the matched kubectl image
- name: KubeSphere | Setting kubectl image version
  set_fact:
    ks_kubectl_tag: "{{ item.value }}"
    kubectl_break: true
  loop: "{{ query('dict', ks_kubectl_versions) }}"
  when:
    - kubectl_break is undefined and kubernetes_version is defined and kubernetes_version is version(item.key, '>=')

- debug:
    msg: Current kubectl image version is {{ ks_kubectl_tag }}

- name: ks-events | Getting ks-events installation files
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.path }}/{{ item.file }}"
  with_items:
    - { path: ks-events, file: custom-values-events.yaml }

- name: ks-events | Deploying ks-events
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/ks-events/kube-events/crds --force &&
    {{ bin_dir }}/helm upgrade --install ks-events
    {{ kubesphere_dir }}/ks-events/kube-events
    -f {{ kubesphere_dir }}/ks-events/custom-values-events.yaml
    -n kubesphere-logging-system --force
  register: events_result
  failed_when: false

- block:
  - name: ks-events | Deploying ks-events
    shell: >
      {{ bin_dir }}/helm del ks-events -n kubesphere-logging-system

  - name: ks-events | Deploying ks-events
    shell: >
      {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/ks-events/kube-events/crds --force &&
      {{ bin_dir }}/helm upgrade --install ks-events
      {{ kubesphere_dir }}/ks-events/kube-events
      -f {{ kubesphere_dir }}/ks-events/custom-values-events.yaml
      -n kubesphere-logging-system --force
    register: events_re_result
    until: events_re_result is succeeded
    retries: 3
    delay: 10

  when:
     - "events_result.stderr and 'field is immutable' in events_result.stderr"

- import_tasks: fluentbit-operator.yaml


- name: ks-events | Importing ks-events status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"events": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kubesphere-system
  register: cc_result
  failed_when: "cc_result.stderr and 'Warning' not in cc_result.stderr"
  until: cc_result is succeeded
  retries: 5
  delay: 3


- name: ks-events | Importing ks-events status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"events": {"ruler": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}}'
    -n kubesphere-system
  register: cc_result
  failed_when: "cc_result.stderr and 'Warning' not in cc_result.stderr"
  until: cc_result is succeeded
  retries: 5
  delay: 3
  when:
    - events is defined
    - events.ruler is defined
    - events.ruler.enabled is defined
    - events.ruler.enabled == True
