{{- if .Values.operator.enabled }}
{{- if or .Values.operator.cleanupAllCustomResources (or .Values.exporter.enabled .Values.ruler.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kube-events.operator.fullname" . }}-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
{{ include "kube-events.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "kube-events.operator.fullname" . }}-cleanup
    spec:
      serviceAccountName: {{ template "kube-events.operator.serviceAccountName" . }}
      containers:
        - name: kubectl
          image: {{ .Values.operator.kubectlImage }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - >
              {{- if .Values.operator.cleanupAllCustomResources }}
              kubectl delete exporter.events.kubesphere.io --all ;
              kubectl delete ruler.events.kubesphere.io --all ;
              kubectl delete rule.events.kubesphere.io --all ;
              {{- else }}
              {{- if .Values.exporter.enabled }}
              kubectl delete exporter.events.kubesphere.io {{ template "kube-events.exporter.fullname" . }} -n {{ .Release.Namespace }} ;
              {{- end }}
              {{- if .Values.ruler.enabled }}
              kubectl delete ruler.events.kubesphere.io {{ template "kube-events.ruler.fullname" . }} -n {{ .Release.Namespace }} ;
              {{- end }}
              {{- end }}
              sleep 10 ;
      restartPolicy: OnFailure
{{- end }}
{{- end }}
