{{- if and .Values.operator.enabled .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-events.operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kube-events.labels" . | indent 4 }}
{{- end }}