---
- block:
  - name: KubeSphere | Getting sonarqube host
    shell: >
      {{ bin_dir }}/kubectl get cm -n kubesphere-system kubesphere-config -o jsonpath='{.data.kubesphere\.yaml}' | grep "sonarQube:" -A 2 | grep "host" | awk '{print $2}'
    register: sonarqube_host

  - name: KubeSphere | Getting sonarqube token
    shell: >
      {{ bin_dir }}/kubectl get cm -n kubesphere-system kubesphere-config -o jsonpath='{.data.kubesphere\.yaml}' | grep "sonarQube:" -A 2 | grep "token" | awk '{print $2}'
    register: sonarqube_token
  when:
    - devops.sonarqube is not defined

- set_fact:
    sonarQubeHost: "{{ sonarqube_host.stdout }}"
    sonarQubeToken: "{{ sonarqube_token.stdout }}"
  when:
    - sonarqube_host is defined and sonarqube_host.stdout is defined and sonarqube_host.stdout != ""
    - sonarqube_token is defined and sonarqube_token.stdout is defined and sonarqube_token.stdout != ""

- set_fact:
    sonarQubeHost: "{{ devops.sonarqube.externalSonarUrl }}"
    sonarQubeToken: "{{ devops.sonarqube.externalSonarToken }}"
  when:
    - devops.sonarqube is defined
    - devops.sonarqube.externalSonarUrl is defined
    - devops.sonarqube.externalSonarToken is defined

- block:
  - name: KubeSphere | Getting es index prefix
    shell: >
      {{ bin_dir }}/kubectl get cm -n kubesphere-system kubesphere-config -o jsonpath='{.data.kubesphere\.yaml}' | grep "logging:" -A 2 | grep "indexPrefix" | awk '{print $2}'
    register: es_indexPrefix

- set_fact:
    esIndexPrefix: "{{ es_indexPrefix.stdout }}"
  when:
    - es_indexPrefix is defined and es_indexPrefix.stdout is defined and es_indexPrefix.stdout != ""

- name: KubeSphere | Getting token
  shell: >
    {{ bin_dir }}/kubectl get secret kubesphere-secret -o jsonpath='{.data.token}' | base64 -d
  register: ks_token_str

- name: KubeSphere | Getting ks-secret
  shell: >
    {{ bin_dir }}/kubectl get secret kubesphere-secret -o jsonpath='{.data.secret}' | base64 -d
  register: ks_secret_str

#- name: KubeSphere | Checking Kubernetes version
#  shell: >
#    {{ bin_dir }}/kubectl version -o json | jq '.serverVersion.gitVersion' | sed s/\"//g
#  register: kubernetes_version

- debug:
    msg: Current Kubernetes version is {{ kubernetes_version }}

# Get the matched kubectl image
- name: KubeSphere | Setting kubectl image version
  set_fact:
    ks_kubectl_tag: "{{ item.value }}"
    kubectl_break: true
  loop: "{{ query('dict', ks_kubectl_versions) }}"
  when:
    - kubectl_break is undefined and kubernetes_version is defined and kubernetes_version is version(item.key, '>=')

- debug:
    msg: Current kubectl image version is {{ ks_kubectl_tag }}

- name: KubeSphere | Getting Kubernetes master num
  shell: >
    {{ bin_dir }}/kubectl get node | awk '{if(NR>1){print $3}}' | grep master | wc -l
  register: masters
  failed_when: false


- name: KubeSphere | Setting master num
  set_fact:
    enableHA: >-
      {% if masters is defined and masters.stdout is defined and masters.stdout != "0" and masters.stdout != "1" %}true{% else %}false{% endif %}
  when:
    - enableHA is not defined

- name: OpenPitrix | Check OpenPitrix v3.0.0
  shell: >
    {{ bin_dir }}/kubectl get deploy openpitrix-hyperpitrix-deployment -n openpitrix-system 2>1 -oNAME | wc -l
  register: openpitrix_deploy_count

- set_fact:
    OPMigrate: true
  when:
    - openpitrix_deploy_count.stdout == "1"

- name: KubeSphere | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.file }}"
  with_items:
    - { name: kubesphere-config, file: kubesphere-config.yaml, type: cm }


- name: KubeSphere | Initing KubeSphere
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/{{ item }}"
  loop:
    - "kubesphere-config.yaml"
  register: init_result
  failed_when: "init_result.stderr and 'AlreadyExists' not in init_result.stderr"

- import_tasks: ks-restart.yaml
