---
devops:
  jenkinsVolumeSize: "8Gi"
  jenkinsMemoryLim: "{{ jenkins_memory_lim |default('8Gi') }}"
  jenkinsMemoryReq: "{{ jenkins_memory_req |default('4Gi') }}"

Java_Opts: -Xms3g -Xmx6g -XX:MaxRAM=8g -Dhudson.slaves.NodeProvisioner.initialDelay=20  -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dhudson.model.LoadStatistics.clock=5000  -Dhudson.model.LoadStatistics.decay=0.2 -Dhudson.slaves.NodeProvisioner.recurrencePeriod=5000 -verbose:gc -Xloggc:/var/jenkins_home/gc-%t.log -XX:NumberOfGCLogFiles=2 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=100m -XX:+PrintGC  -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions
JavaOpts: >
  -Xms{{ devops.jenkinsJavaOpts_Xms | default('3g') }}
  -Xmx{{ devops.jenkinsJavaOpts_Xmx | default('6g') }}
  -XX:MaxRAM={{ devops.jenkinsJavaOpts_MaxRAM | default('8g') }}
  -Dhudson.slaves.NodeProvisioner.initialDelay=20
  -Dhudson.slaves.NodeProvisioner.MARGIN=50
  -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
  -Dhudson.model.LoadStatistics.clock=5000
  -Dhudson.model.LoadStatistics.decay=0.2
  -Dhudson.slaves.NodeProvisioner.recurrencePeriod=5000
  -Dio.jenkins.plugins.casc.ConfigurationAsCode.initialDelay=10000
  -verbose:gc
  -Xloggc:/var/jenkins_home/gc-%t.log
  -XX:NumberOfGCLogFiles=2
  -XX:+UseGCLogFileRotation
  -XX:GCLogFileSize=100m
  -XX:+PrintGC
  -XX:+PrintGCDateStamps
  -XX:+PrintGCDetails
  -XX:+PrintHeapAtGC
  -XX:+PrintGCCause
  -XX:+PrintTenuringDistribution
  -XX:+PrintReferenceGC
  -XX:+PrintAdaptiveSizePolicy
  -XX:+UseG1GC
  -XX:+UseStringDeduplication
  -XX:+ParallelRefProcEnabled
  -XX:+DisableExplicitGC
  -XX:+UnlockDiagnosticVMOptions
  -XX:+UnlockExperimentalVMOptions

JenkinsLocationUrl: jenkins.devops.kubesphere.local

EMAIL_SMTP_HOST: mail.example.com
EMAIL_FROM_ADDR: admin@example.com
EMAIL_FROM_NAME: KubeSphere
EMAIL_USE_SSL: false
EMAIL_SMTP_PORT: 465
EMAIL_FROM_PASS: P@ssw0rd

sonar_account_user: ks-devops

harbor_domain: harbor.devops.kubesphere.local


sonarqube_enable: true

sonarqube_user_name: sonarqube
sonarqube_user_passwd: sonarqube
