---

- name: ks-apigateway | Getting ks-apigateway installation files
  copy:
    src: "ks-apigateway"
    dest: "{{ kubesphere_dir }}/"
  tags:
    - upgrade

- name: ks-apigateway | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/ks-apigateway/{{ item.file }}"
  with_items:
    - { name: ks-apigateway, file: ks-apigateway.yaml, type: deploy }
  tags:
    - upgrade

- name: ks-apigateway | Installing ks-apigateway
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/ks-apigateway/ks-apigateway.yaml --force
  register: import
  failed_when: "import.stderr and 'has been modified' not in import.stderr"
  tags:
    - upgrade

- name: KubeSphere | Restarting ks-apigateway
  shell: >
    {{ bin_dir }}/kubectl -n kubesphere-system scale deployment ks-apigateway --replicas=0 && 
    {{ bin_dir }}/kubectl -n kubesphere-system scale deployment ks-apigateway --replicas=1
  tags:
    - upgrade