apiVersion: rbac.authorization.k8s.io/v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: prometheus-k8s
      namespace: default
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: prometheus-k8s
    subjects:
      - kind: ServiceAccount
        name: prometheus-k8s
        namespace: kubesphere-monitoring-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: prometheus-k8s
      namespace: kube-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: prometheus-k8s
    subjects:
      - kind: ServiceAccount
        name: prometheus-k8s
        namespace: kubesphere-monitoring-system
#  - apiVersion: rbac.authorization.k8s.io/v1
#    kind: RoleBinding
#    metadata:
#      name: prometheus-k8s
#      namespace: istio-system
#    roleRef:
#      apiGroup: rbac.authorization.k8s.io
#      kind: Role
#      name: prometheus-k8s
#    subjects:
#      - kind: ServiceAccount
#        name: prometheus-k8s
#        namespace: kubesphere-monitoring-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: prometheus-k8s
      namespace: kubesphere-monitoring-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: prometheus-k8s
    subjects:
      - kind: ServiceAccount
        name: prometheus-k8s
        namespace: kubesphere-monitoring-system
kind: RoleBindingList
