appVersion: "7.6"
description: Sonarqube is an open sourced code quality scanning tool
home: https://www.sonarqube.org/
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
keywords:
- coverage
- security
- code
- quality
maintainers:
- email: rjkernick@gmail.com
  name: rjkernick
name: sonarqube
sources:
- https://github.com/SonarSource/docker-sonarqube
version: 0.13.5
