---

- import_tasks: init-namespaces.yaml


- name: KubeSphere | Getting kubernetes master num
  shell: >
    {{ bin_dir }}/kubectl get node | awk '{if(NR>1){print $3}}' | grep master |wc -l
  register: masters
  ignore_errors: True


- name: KubeSphere | Setting master num
  set_fact:
    enableHA: >-
      {% if masters is defined and masters.stdout is defined and masters.stdout != "0" and masters.stdout != "1" %}true{% else %}false{% endif %}


- name: Kubesphere | Getting common component installation files
  copy:
    src: "{{ item }}"
    dest: "{{ kubesphere_dir }}/"
  loop:
    - "common"
    - "ks-crds"


- name: KubeSphere | Create KubeSphere crds
  shell: "{{ bin_dir }}/kubectl create -R -f {{ kubesphere_dir }}/ks-crds/"
  register: import
  failed_when: "import.stderr and 'AlreadyExists' not in import.stderr"


- name: KubeSphere | check k8s version
  shell: >
    {{ bin_dir }}/kubectl version -o json | jq '.serverVersion.gitVersion' | sed s/\"//g
  register: kubernetes_version

- name: Kubesphere | Deploy snapshot controller
  block:
    - name: Kubesphere | Getting common component installation files
      copy:
        src: "{{ item }}"
        dest: "{{ kubesphere_dir }}/"
      loop:
        - "snapshot-controller"

    - name: Kubesphere | Creating snapshot controller values
      template:
        src: "{{ item.file }}.j2"
        dest: "{{ kubesphere_dir }}/{{ item.file }}"
      with_items:
        - { name: custom-values-snapshot-controller, file: custom-values-snapshot-controller.yaml }

    - name: Kubesphere | Remove old snapshot crd
      command: >
        {{ bin_dir }}/kubectl delete -f {{ kubesphere_dir }}/snapshot-controller/crds/snapshot.storage.k8s.io_volumesnapshot.yaml
      ignore_errors: True

    - name: Kubesphere | Deploy snapshot controller
      shell: >
        {{ bin_dir }}/helm upgrade --install snapshot-controller
        {{ kubesphere_dir }}/snapshot-controller
        -f {{ kubesphere_dir }}/custom-values-snapshot-controller.yaml
        --namespace kube-system
  when:
    - kubernetes_version.stdout is version('v1.17.0', '>=')


- name: Kubesphere | Checking openpitrix common component
  shell: >
    {{ bin_dir }}/kubectl get pod -n openpitrix-system
  register: openpitrix_component_pod


- include_tasks: pv-migration.yaml
  loop:
    - {op: "openpitrix-db", ks: "mysql-pvc"}
    - {op: "openpitrix-etcd", ks: "etcd-pvc"}
#    - {openpitrix: "openpitrix-minio", ks: "minio-pvc"}
  when:
    - openpitrix_component_pod.stdout.find("openpitrix-db-deployment") != -1


- name: Kubesphere | Getting PersistentVolumeName (mysql/etcd/minio)
  block:

    - name: Getting PersistentVolumeName (mysql)
      shell: >
        kubectl get pv | grep "kubesphere-system/mysql-pvc" | awk '{print $1}'
      register: pvName
    - name: Getting PersistentVolumeSize (mysql)
      shell: >
        kubectl get pv | grep "kubesphere-system/mysql-pvc" | awk '{print $2}'
      register: pvSize

    - name: Setting PersistentVolumeName (mysql)
      set_fact:
        db_pv_name: "{{ pvName.stdout }}"
    - name: Setting PersistentVolumeSize (mysql)
      set_fact:
        common:
          mysqlVolumeSize: "{{ pvSize.stdout }}"


    - name: Getting PersistentVolumeName (etcd)
      shell: >
        kubectl get pv | grep "kubesphere-system/etcd-pvc" | awk '{print $1}'
      register: pvName
    - name: Getting PersistentVolumeSize (etcd)
      shell: >
        kubectl get pv | grep "kubesphere-system/etcd-pvc" | awk '{print $2}'
      register: pvSize

    - name: Setting PersistentVolumeName (etcd)
      set_fact:
        etcd_pv_name: "{{ pvName.stdout }}"
    - name: Setting PersistentVolumeSize (etcd)
      set_fact:
        common:
          etcdVolumeSize: "{{ pvSize.stdout}}"


  when:
    - openpitrix_component_pod.stdout.find("openpitrix-db-deployment") != -1

- import_tasks: get_old_config.yaml

- name: Kubesphere | Creating common component manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/common/{{ item.file }}"
  with_items:
    - { path: etcd, file: etcd.yaml }
    - { name: mysql, file: mysql.yaml }
    - { path: redis, file: redis.yaml }


- name: Kubesphere | Creating mysql sercet
  shell: >
    {{ bin_dir }}/kubectl create secret generic mysql-pass
    --from-file={{ kubesphere_dir }}/common/password.txt
    -n kubesphere-system
  register: import
  failed_when: "import.stderr and 'AlreadyExists' not in import.stderr"

- name: Kubesphere | Deploying common component
  block:
    - name: Kubesphere | Deploying etcd and mysql
      shell: >
        {{ bin_dir }}/kubectl -n kubesphere-system apply -f {{ kubesphere_dir }}/common/{{ item }}
      loop:
        - "etcd.yaml"
        - "mysql.yaml"
      register: import
      failed_when:
        - "import.stderr and 'is immutable after creation except resources.requests for bound claims' not in import.stderr"
        - "import.stderr and 'is forbidden' not in import.stderr"


    - import_tasks: minio-install.yaml


    - import_tasks: redis-install.yaml


    - import_tasks: openldap-install.yaml

  when:
    - openpitrix_component_pod.stdout.find("openpitrix-db-deployment") != -1


- import_tasks: common-install.yaml
  when:
    - openpitrix_component_pod.stdout.find("openpitrix-db-deployment") == -1


- name: Kubesphere | Setting persistentVolumeReclaimPolicy (mysql/etcd/minio)
  block:

    - name: Setting persistentVolumeReclaimPolicy (mysql)
      shell: >
        kubectl patch pv $(kubectl get pv | grep "mysql-pvc" | awk '{print $1}')
        -p '{"spec":{"persistentVolumeReclaimPolicy": "Delete"}}'

    - name: Setting persistentVolumeReclaimPolicy (etcd)
      shell: >
        kubectl patch pv $(kubectl get pv | grep "etcd-pvc" | awk '{print $1}')
        -p '{"spec":{"persistentVolumeReclaimPolicy": "Delete"}}'

  when:
    - openpitrix_component_pod.stdout.find("openpitrix-db-deployment") != -1