- name: Empty backup directory
  file:
    state: absent
    path: "/tmp/minio-backup/{{ item }}/"

- name: Recreate backup directory
  file:
    state: directory
    path: "/tmp/minio-backup/{{ item }}/"

- name: KubeSphere | Fetch openpitrix-minio data
  shell: >
    rclone copy
    op-minio:openpitrix-internal-repo/{{ item }}
    /tmp/minio-backup/{{ item }}/

- name: KubeSphere | Checking minio status
  shell: >
    {{ bin_dir }}/kubectl get pod -n kubesphere-system | grep 'minio' | grep -v 'Running' | wc -l
  register: minio_status
  until: minio_status.stdout == "0"
  retries: 30
  delay: 30

- name: KubeSphere | Sync openpitrix-minio data
  shell: >
    rclone copy
    /tmp/minio-backup/{{ item }}/
    ks-minio:openpitrix-internal-repo/{{ item }}
