
- name: KubeSphere | Deploying common component
  shell: >
    {{ bin_dir }}/kubectl -n kubesphere-system apply -f {{ kubesphere_dir }}/common/{{ item }}
  loop:
    - "mysql.yaml"
  register: import
  failed_when:
    - "import.stderr and 'is immutable after creation except resources.requests for bound claims' not in import.stderr"
    - "import.stderr and 'is forbidden' not in import.stderr"
#  when: devops.enabled or openpitrix.enabled or notification.enabled or alerting.enabled

- name: KubeSphere | Import mysql status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"mysql": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kubesphere-system
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3