apiVersion: v1
data:
  template: |2

    {{ "{{ define \"nm.default.subject\" }}{{ .Alerts | len }} alert{{ if gt (len .Alerts) 1 }}s{{ end }} for {{ range .GroupLabels.SortedPairs }} {{ .Name }}={{ .Value }} {{ end }}" }}
    {{ "{{- end }}" }}

    {{ "{{ define \"__nm_alert_list\" }}{{ range . }}Labels:" }}
    {{ "{{ range .Labels.SortedPairs }}{{ if ne .Name \"runbook_url\" }}- {{ .Name }} = {{ .Value }}{{ end }}" }}
    {{ "{{ end }}Annotations:" }}
    {{ "{{ range .Annotations.SortedPairs }}{{ if ne .Name \"runbook_url\"}}- {{ .Name }} = {{ .Value }}{{ end }}" }}
    {{ "{{ end }}{{ end }}{{ end }}" }}

    {{ "{{ define \"nm.default.text\" }}{{ template \"nm.default.subject\" . }}" }}
    {{ "{{ if gt (len .Alerts.Firing) 0 -}}" }}
    {{ "Alerts Firing:" }}
    {{ "{{ template \"__nm_alert_list\" .Alerts.Firing }}" }}
    {{ "{{- end }}" }}
    {{ "{{ if gt (len .Alerts.Resolved) 0 -}}" }}
    {{ "Alerts Resolved:" }}
    {{ "{{ template \"__nm_alert_list\" .Alerts.Resolved }}" }}
    {{ "{{- end }}" }}
    {{ "{{- end }}" }}

    {{ "{{ define \"__nm_alert_list_markdown\" }}{{ range . }}### Labels:" }}
    {{ "{{ range .Labels.SortedPairs }}{{ if ne .Name \"runbook_url\" }}- {{ .Name }} = {{ .Value }}{{ end }}" }}
    {{ "{{ end }}### Annotations:" }}
    {{ "{{ range .Annotations.SortedPairs }}{{ if ne .Name \"runbook_url\"}}- {{ .Name }} = {{ .Value }}{{ end }}" }}
    {{ "{{ end }}{{ end }}{{ end }}" }}

    {{ "{{ define \"nm.default.markdown\" }}# {{ template \"nm.default.subject\" . }}" }}
    {{ "{{ if gt (len .Alerts.Firing) 0 -}}" }}
    {{ "## <font color=#CD0000>Alerts Firing:</font>" }}
    {{ "{{ template \"__nm_alert_list_markdown\" .Alerts.Firing }}" }}
    {{ "{{- end }}" }}
    {{ "{{ if gt (len .Alerts.Resolved) 0 -}}" }}
    {{ "## <font color=#00CD00>Alerts Resolved:</font>" }}
    {{ "{{ template \"__nm_alert_list_markdown\" .Alerts.Resolved }}" }}
    {{ "{{- end }}" }}
    {{ "{{- end }}" }}

    {{ "{{ define \"nm.default.html\" }}" }}
    {{ "  <html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns=\"http://www.w3.org/1999/xhtml\" style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "  <head style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "    <meta name=\"viewport\" content=\"width=device-width\" style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />" }}
    {{ "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />" }}
    {{ "    <title style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">{{ template \"__subject\" . }}</title>" }}
    {{ "  </head>" }}
    {{ "  <body itemscope=\"\" itemtype=\"http://schema.org/EmailMessage\" style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; height: 100%; line-height: 1.6em; width: 100% !important; background-color: #f6f6f6; margin: 0; padding: 0;\" bgcolor=\"#f6f6f6\">" }}
    {{ "  <table style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; background-color: #f6f6f6; margin: 0;\" bgcolor=\"#f6f6f6\">" }}
    {{ "    <tr style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "      <td style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;\" valign=\"top\"></td>" }}
    {{ "      <td width=\"600\" style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 600px !important; clear: both !important; width: 100% !important; margin: 0 auto; padding: 0;\" valign=\"top\">" }}
    {{ "        <div style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; max-width: 600px; display: block; margin: 0 auto; padding: 0;\">" }}
    {{ "          <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; border-radius: 3px; background-color: #fff; margin: 0; border: 1px solid #e9e9e9;\" bgcolor=\"#fff\">" }}
    {{ "            <tr style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "              <td style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; vertical-align: top; color: #fff; font-weight: 500; text-align: center; border-radius: 3px 3px 0 0; background-color: #E6522C; margin: 0; padding: 20px;\" align=\"center\" bgcolor=\"#E6522C\" valign=\"top\">" }}
    {{ "                {{ .Alerts | len }} alert{{ if gt (len .Alerts) 1 }}s{{ end }} for {{ range .GroupLabels.SortedPairs }}" }}
    {{ "                  {{ .Name }}={{ .Value }}" }}
    {{ "                {{ end }}" }}
    {{ "              </td>" }}
    {{ "            </tr>" }}
    {{ "            <tr style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "              <td style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 10px;\" valign=\"top\">" }}
    {{ "                <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "                  {{ if gt (len .Alerts.Firing) 0 }}" }}
    {{ "                    <tr style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "                      <td style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;\" valign=\"top\">" }}
    {{ "                        <strong style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">[{{ .Alerts.Firing | len }}] Firing</strong>" }}
    {{ "                     </td>" }}
    {{ "                    </tr>" }}
    {{ "                  {{ end }}" }}
    {{ "                  {{ range .Alerts.Firing }}" }}
    {{ "                    <tr style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "                      <td style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;\" valign=\"top\">" }}
    {{ "                        <strong style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">Labels</strong><br style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />" }}
    {{ "                        {{ range .Labels.SortedPairs }}{{ if ne .Name \"runbook_url\" }}{{ .Name }} = {{ .Value }}{{ end }}<br style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />{{ end }}" }}
    {{ "                        {{ if gt (len .Annotations) 0 }}<strong style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">Annotations</strong><br style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />{{ end }}" }}
    {{ "                        {{ range .Annotations.SortedPairs }}{{ if ne .Name \"runbook_url\" }}{{ .Name }} = {{ .Value }}{{ end }}<br style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />{{ end }}" }}
    {{ "                      </td>" }}
    {{ "                    </tr>" }}
    {{ "                  {{ end }}" }}
    {{ "                  {{ if gt (len .Alerts.Resolved) 0 }}" }}
    {{ "                    {{ if gt (len .Alerts.Firing) 0 }}" }}
    {{ "                      <tr style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "                        <td style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;\" valign=\"top\">" }}
    {{ "                          <br style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />" }}
    {{ "                          <hr style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />" }}
    {{ "                          <br style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />" }}
    {{ "                        </td>" }}
    {{ "                      </tr>" }}
    {{ "                    {{ end }}" }}
    {{ "                    <tr style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "                      <td style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;\" valign=\"top\">" }}
    {{ "                        <strong style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">[{{ .Alerts.Resolved | len }}] Resolved</strong>" }}
    {{ "                      </td>" }}
    {{ "                    </tr>" }}
    {{ "                  {{ end }}" }}
    {{ "                  {{ range .Alerts.Resolved }}" }}
    {{ "                    <tr style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">" }}
    {{ "                      <td style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;\" valign=\"top\">" }}
    {{ "                        <strong style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">Labels</strong><br style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />" }}
    {{ "                        {{ range .Labels.SortedPairs }}{{ if ne .Name \"runbook_url\" }}{{ .Name }} = {{ .Value }}{{ end }}<br style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />{{ end }}" }}
    {{ "                        {{ if gt (len .Annotations) 0 }}<strong style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\">Annotations</strong><br style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />{{ end }}" }}
    {{ "                        {{ range .Annotations.SortedPairs }}{{ if ne .Name \"runbook_url\" }}{{ .Name }} = {{ .Value }}{{ end }}<br style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;\" />{{ end }}" }}
    {{ "                       </td>" }}
    {{ "                     </tr>" }}
    {{ "                   {{ end }}" }}
    {{ "                 </table>" }}
    {{ "               </td>" }}
    {{ "             </tr>" }}
    {{ "           </table>" }}
    {{ "        </div>" }}
    {{ "      </td>" }}
    {{ "      <td style=\"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;\" valign=\"top\"></td>" }}
    {{ "    </tr>" }}
    {{ "  </table>" }}
    {{ "  </body>" }}
    {{ "  </html>" }}
    {{ "{{ end }}" }}
kind: ConfigMap
metadata:
  name: notification-manager-template
  namespace: kubesphere-monitoring-system