
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: rules.events.kubesphere.io
spec:
  group: events.kubesphere.io
  names:
    kind: Rule
    listKind: RuleList
    plural: rules
    shortNames:
    - er
    singular: rule
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: Rule is the Schema for the Rule API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RuleSpec defines the desired state of Rule
          properties:
            rules:
              items:
                description: EventRule describes a notification or alert rule
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    description: 'Values of Annotations can use format string with
                      the fields of the event. For example: `{"message": "%message"}`'
                    type: object
                  condition:
                    description: 'Condition is a string similar with the where part
                      of sql. See supported grammar details on https://github.com/kubesphere/event-rule-engine#supported-grammer
                      . For example: `type="Warning" and involvedObject.kind="Pod"
                      and reason="FailedMount"`'
                    type: string
                  enable:
                    description: Enable is whether to enable the rule, default to
                      `false`
                    type: boolean
                  labels:
                    additionalProperties:
                      type: string
                    description: Labels
                    type: object
                  name:
                    description: Name is simple name of rule
                    type: string
                  type:
                    description: Type represents that the rule is for notification
                      or alert. Available values are `notification` and `alert`
                    type: string
                type: object
              type: array
          type: object
        status:
          description: RuleStatus defines the observed state of Rule
          type: object
      required:
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
