---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-api-gateway-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-api-gateway-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-app-manager-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-app-manager-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-category-manager-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-category-manager-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-cluster-manager-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-cluster-manager-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-db-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-db-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-etcd-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-etcd-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-iam-service-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-iam-service-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-job-manager-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-job-manager-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-minio-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-minio-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-repo-indexer-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-repo-indexer-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-repo-manager-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-repo-manager-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-runtime-manager-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-runtime-manager-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openpitrix-task-manager-vpa
  namespace: openpitrix-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openpitrix-task-manager-deployment
    namespace: openpitrix-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-account-vpa
  namespace: kubesphere-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: ks-account
    namespace: kubesphere-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-apigateway-vpa
  namespace: kubesphere-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: ks-apigateway
    namespace: kubesphere-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-apiserver-vpa
  namespace: kubesphere-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: ks-apiserver
    namespace: kubesphere-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-console-vpa
  namespace: kubesphere-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: ks-console
    namespace: kubesphere-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: openldap-vpa
  namespace: kubesphere-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: openldap
    namespace: kubesphere-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
  namespace: kubesphere-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: redis
    namespace: kubesphere-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-jenkins-vpa
  namespace: kubesphere-devops-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: ks-jenkins
    namespace: kubesphere-devops-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-s2ioperator-vpa
  namespace: kubesphere-devops-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: s2ioperator
    namespace: kubesphere-devops-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: kube-state-metrics-vpa
  namespace: kubesphere-monitoring-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: kube-state-metrics
    namespace: kubesphere-monitoring-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-prometheus-operator-vpa
  namespace: kubesphere-monitoring-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: prometheus-operator
    namespace: kubesphere-monitoring-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-prometheus-k8s-vpa
  namespace: kubesphere-monitoring-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: prometheus-k8s
    namespace: kubesphere-monitoring-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-prometheus-k8s-system-vpa
  namespace: kubesphere-monitoring-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: prometheus-k8s-system
    namespace: kubesphere-monitoring-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-elasticsearch-logging-data-vpa
  namespace: kubesphere-logging-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: elasticsearch-logging-data
    namespace: kubesphere-logging-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-elasticsearch-logging-discovery-vpa
  namespace: kubesphere-logging-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: elasticsearch-logging-discovery
    namespace: kubesphere-logging-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-fluent-bit-vpa
  namespace: kubesphere-logging-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: DaemonSet
    name: fluent-bit
    namespace: kubesphere-logging-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-logging-fluentbit-operator-vpa
  namespace: kubesphere-logging-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: logging-fluentbit-operator
    namespace: kubesphere-logging-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-alerting-client-vpa
  namespace: kubesphere-alerting-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: alerting-client
    namespace: kubesphere-alerting-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-alerting-executor-vpa
  namespace: kubesphere-alerting-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: alerting-executor
    namespace: kubesphere-alerting-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-alerting-manager-vpa
  namespace: kubesphere-alerting-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: alerting-manager
    namespace: kubesphere-alerting-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-alerting-watcher-vpa
  namespace: kubesphere-alerting-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: alerting-watcher
    namespace: kubesphere-alerting-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-notification-deployment-vpa
  namespace: kubesphere-alerting-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: notification-deployment
    namespace: kubesphere-alerting-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-istio-citadel-vpa
  namespace: istio-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: istio-citadel
    namespace: istio-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-istio-galley-vpa
  namespace: istio-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: istio-galley
    namespace: istio-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-istio-ingressgateway-vpa
  namespace: istio-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: istio-ingressgateway
    namespace: istio-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-istio-pilot-vpa
  namespace: istio-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: istio-pilot
    namespace: istio-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-istio-policy-vpa
  namespace: istio-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: istio-policy
    namespace: istio-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-istio-sidecar-injector-vpa
  namespace: istio-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: istio-sidecar-injector
    namespace: istio-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-istio-telemetry-vpa
  namespace: istio-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: istio-telemetry
    namespace: istio-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-jaeger-collector-vpa
  namespace: istio-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: jaeger-collector
    namespace: istio-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-jaeger-operator-vpa
  namespace: istio-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: jaeger-operator
    namespace: istio-system

---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ks-jaeger-query-vpa
  namespace: istio-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: jaeger-query
    namespace: istio-system

