apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: thanos-ruler
    app.kubernetes.io/instance: kubesphere
    app.kubernetes.io/name: thanos-ruler
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.28.5
  name: thanos-ruler-kubesphere
  namespace: kubesphere-monitoring-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: thanos-ruler
      app.kubernetes.io/instance: kubesphere
      app.kubernetes.io/name: thanos-ruler
      app.kubernetes.io/part-of: kube-prometheus
