- name: servicemesh | Checking jaeger-operator
  shell: >
    {{ bin_dir }}/helm list -n istio-system | grep "jaeger-operator"
  register: jaeger_check
  failed_when: false

- name: servicemesh | Deleting jaeger-operator deployment
  shell: >
    {{ bin_dir }}/kubectl -n istio-system delete deployment jaeger-operator
  when:
    - (jaeger_check.stdout.find("deployed") != -1) and (jaeger_check.stdout.find("1.29.1") == -1)
  ignore_errors: True

- name: servicemesh | Deploying jaeger-operator
  shell: >
    {{ bin_dir }}/helm upgrade --install jaeger-operator {{ kubesphere_dir }}/servicemesh/jaeger/jaeger-operator-2.29.0.tgz
    -f {{ kubesphere_dir }}/servicemesh/jaeger/custom-values-jaeger.yaml
    --namespace istio-system
  when:
    - (jaeger_check.stdout.find("deployed") == -1) or (jaeger_check.stdout.find("1.29.1") == -1)

- name: servicemesh | Deploying es jaeger-secret
  shell: >
    {{ bin_dir }}/kubectl create secret generic jaeger-secret
    --from-literal=ES_PASSWORD={{ common.es.basicAuth.password }}
    --from-literal=ES_USERNAME={{ common.es.basicAuth.username }}
    --namespace istio-system
    --dry-run=client -oyaml | {{ bin_dir }}/kubectl apply -f -
  register: jaeger_result
  until: jaeger_result is succeeded
  retries: 5
  delay: 10
  when:
    - "common.es.basicAuth.enabled is defined"
    - "common.es.basicAuth.enabled == true"
    - "common.es.basicAuth.password is defined and common.es.basicAuth.password != ''"
    - "common.es.basicAuth.username is defined and common.es.basicAuth.username != ''"
    - "common.es is defined and common.es.enabled is defined and common.es.enabled"

- name: servicemesh | Deploying opensearch jaeger-secret
  shell: >
    {{ bin_dir }}/kubectl create secret generic jaeger-secret
    --from-literal=ES_PASSWORD={{ common.opensearch.basicAuth.password }}
    --from-literal=ES_USERNAME={{ common.opensearch.basicAuth.username }}
    --namespace istio-system
    --dry-run=client -oyaml | {{ bin_dir }}/kubectl apply -f -
  register: jaeger_result
  until: jaeger_result is succeeded
  retries: 5
  delay: 10
  when:
    - "common.opensearch.basicAuth.enabled is defined"
    - "common.opensearch.basicAuth.enabled == true"
    - "common.opensearch.basicAuth.password is defined and common.opensearch.basicAuth.password != ''"
    - "common.opensearch.basicAuth.username is defined and common.opensearch.basicAuth.username != ''"
    - "common.opensearch is defined and common.opensearch.enabled is defined and common.opensearch.enabled"

- name: servicemesh | Deploying jaeger-cr
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/servicemesh/jaeger/jaeger-cr.yaml --namespace istio-system"
  register: jaeger_cr_result
  until: jaeger_cr_result is succeeded
  retries: 5
  delay: 10
  when:
    - (jaeger_check.stdout.find("deployed") == -1) or (jaeger_check.stdout.find("1.29.1") == -1)
