- name: servicemesh | Checking kiali-operator
  shell: >
    {{ bin_dir }}/helm list -n istio-system | grep "kiali-operator"
  register: kiali_check
  failed_when: false

- name: servicemesh | Deleting kiali operator deployment
  shell: >
    {{ bin_dir }}/kubectl -n istio-system delete deployment kiali-operator
  when:
    - (kiali_check.stdout.find("deployed") != -1) and (kiali_check.stdout.find("v1.50.1") == -1)
  ignore_errors: True

- name: servicemesh | Deploying kiali-operator
  shell: >
    {{ bin_dir }}/helm upgrade --install kiali-operator {{ kubesphere_dir }}/servicemesh/kiali/kiali-operator-1.50.1.tgz
    -f {{ kubesphere_dir }}/servicemesh/kiali/custom-values-kiali.yaml
    --namespace istio-system
  when:
    - (kiali_check.stdout.find("deployed") == -1) or (kiali_check.stdout.find("v1.50.1") == -1)

- name: servicemesh | Deploying kiali-cr
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/servicemesh/kiali/kiali-cr.yaml --namespace istio-system"
  register: kiali_cr_result
  until: kiali_cr_result is succeeded
  retries: 5
  delay: 10
  when:
    - (kiali_check.stdout.find("deployed") == -1) or (kiali_check.stdout.find("v1.50.1") == -1)
