---

dbHost: kubesphere-db.kubesphere-system.svc
dbPort: 3306

etcdHost: kubesphere-etcd.kubesphere-system.svc
etcdPort: 2379
etcdEndpoint: "{{ etcdHost }}:{{ etcdPort }}"

redisHost: redis.kubesphere-system.svc
redisPort: 6379
redisEndpoint: "{{ redisHost }}:{{ redisPort }}"