---

dbHost: mysql.kubesphere-system.svc
dbPort: 3306

etcdHost: etcd.kubesphere-system.svc
etcdPort: 2379
etcdEndpoint: "{{ etcdHost }}:{{ etcdPort }}"

redisHost: redis-haproxy.kubesphere-system.svc
redisPort: 6379
redisEndpoint: "{{ redisHost }}:{{ redisPort }}"