name: Deploy-Test

on:
  push:
    branches: master
 
  schedule:
    - cron:  '0 1 * * *'

jobs:
  Deploy-Test:
    runs-on: ubuntu-latest
    if: github.repository	== 'kubesphere/ks-installer'
    timeout-minutes: 150
    env:
      working-directory: ./.github/workflows/deploy-test
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST }}
    steps:
    - uses: actions/checkout@v2.1.1

    - name: setup terraform
      working-directory: ${{env.working-directory}}
      run: |
        wget https://releases.hashicorp.com/terraform/0.13.0/terraform_0.13.0_linux_amd64.zip
        unzip terraform_0.13.0_linux_amd64.zip

    - name: setup secret
      working-directory: ${{env.working-directory}}
      run: |
        sed -i 's/yourID/${{ secrets.QINGCLOUD_ACCESS_KEY }}/' var.tf
        sed -i 's/yourSecret/${{ secrets.QINGCLOUD_SECRET_KEY }}/' var.tf
    
    - name: install kubesphere
      working-directory: ${{env.working-directory}}
      timeout-minutes: 90
      run: |
        terraform init
        terraform apply -input=false -auto-approve

    - name: destory
      working-directory: ${{env.working-directory}}
      run: |
        echo 'yes' | terraform destroy
      if: always()

    - name: slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      if: always()
